### ISSUE TITLE
Thank you,

### ISSUE THREAD

**Issue by lohtse** [M7SPI/Quansheng-UV-K5-UK-Regional-Channel-Settings-File#1]
Thank you for providing these.. 

Any chance of one for Oxford northamptons area???

great work and thank you

**Comment by M7SPI** [comment]
Good afternoon,
Of course I can, im just back from a long weekend in Blackpool with my family so will create one a little later today.

I will post on GitHub and release it on our group on facebook if you use social media, the group is Quansheng uv-k5 UK users https://www.facebook.com/groups/2291286734508728

All the best,

Stu – M7SPI

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: 20 August 2023 19:28
To: ***@***.***>
Cc: ***@***.***>
Subject: [M7SPI/Quansheng-UV-K5-UK-Regional-Channel-Settings-File] Thank you, (Issue #1)


Thank you for providing these..

Any chance of one for Oxford northamptons area???

great work and thank you

**Comment by M7SPI** [comment]
Their you go mate https://github.com/M7SPI/Quansheng-UV-K5-UK-Regional-Channel-Settings-File/blob/main/Quansheng_UV-K5_PMR_2Meters_70cm_Oxford_Northampton.img

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: 20 August 2023 19:28
To: ***@***.***>
Cc: ***@***.***>
Subject: [M7SPI/Quansheng-UV-K5-UK-Regional-Channel-Settings-File] Thank you, (Issue #1)


Thank you for providing these..

Any chance of one for Oxford northamptons area???

great work and thank you

**Comment by lohtse** [comment]
Thank you buddy.... Nice work and very much appreciated... Took a gander at you website. Fantastic work!!!!!!!!!!!

**Comment by lohtse** [comment]
you may want to take a look at this 

https://github.com/egzumer/uv-k5-firmware-custom


possible the best FW for the K5s


if you need one compiling too your requirements.. I'm happy to help..


Least I can do for the work you put in here.

**Comment by M7SPI** [comment]
> you may want to take a look at this
> 
> https://github.com/egzumer/uv-k5-firmware-custom
> 
> possible the best FW for the K5s
> 
> if you need one compiling too your requirements.. I'm happy to help..
> 
> Least I can do for the work you put in here.

I already use it mate a great source.

**Comment by M7SPI** [comment]
Scratch that i didnt realise it was your own repo. Currently using a oneofeleven firmaware mod

**Comment by lohtse** [comment]
Not mine another devsbthat combines 1of1i with spectrum app
